<ips:template parameters="" />
<h1 class="ipsType_pageTitle ipsFlex-flex:11 ipsType_break ipsMargin_bottom title">
  {lang="hello_world_test_page"} - {setting="aXenHelloWorld_settings_title"}
</h1>

{{if settings.aXenHelloWorld_settings_title}}
<div>Test</div>
{{endif}}

<div class='ipsBox ipsPadding'>
  <div class='ipsMessage ipsMessage_error'>
    <span class='ipsMessage_code'>12345</span>
    This is an error message.
  </div>

  <img src='{resource="logo_dark.png" app="helloworld" location="front"}' alt='Logo aXenDev'>

  Created by aXenDev!
</div>